In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating Tensors

In [3]:
# Scaler

scaler = torch.tensor(7)
print(scaler)
print(type(scaler))

tensor(7)
<class 'torch.Tensor'>


In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
# Vector

vector = torch.tensor([7,7])
print(vector)
print(type(vector))

tensor([7, 7])
<class 'torch.Tensor'>


In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

matrix = torch.tensor([[1,2],[5,6]])
print(matrix)
print(type(matrix))

tensor([[1, 2],
        [5, 6]])
<class 'torch.Tensor'>


In [10]:
matrix.ndim

2

In [11]:
print(matrix[:][1])
print(matrix[0])

tensor([5, 6])
tensor([1, 2])


In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
tensor = torch.tensor([[[1,2,3,9],
                        [4,5,6,2],
                        [7,8,9,5]]])

In [14]:
tensor

tensor([[[1, 2, 3, 9],
         [4, 5, 6, 2],
         [7, 8, 9, 5]]])

In [15]:
tensor.shape

torch.Size([1, 3, 4])

In [16]:
tensor.ndim

3

### Random Tensors

In [17]:
### Create a Random Tensor

random_tensor = torch.rand(2,4,5)
random_tensor

tensor([[[0.1365, 0.7738, 0.6261, 0.8538, 0.5491],
         [0.8901, 0.9058, 0.2734, 0.1613, 0.4140],
         [0.5398, 0.0134, 0.5549, 0.3613, 0.9841],
         [0.0966, 0.7228, 0.8738, 0.0924, 0.8596]],

        [[0.1841, 0.2388, 0.7284, 0.6160, 0.1673],
         [0.1894, 0.2129, 0.4682, 0.5362, 0.6115],
         [0.8178, 0.6218, 0.0786, 0.3585, 0.3025],
         [0.2909, 0.4370, 0.2256, 0.0301, 0.0732]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_tensor.shape

torch.Size([2, 4, 5])

In [20]:
### Craeate a random tensor with similar shape to an image

random_tensor_img_size = torch.rand(size=(3,224,224))
random_tensor_img_size

tensor([[[0.9291, 0.3775, 0.3214,  ..., 0.9854, 0.8964, 0.5872],
         [0.1655, 0.6723, 0.3133,  ..., 0.6451, 0.8160, 0.3830],
         [0.3813, 0.6565, 0.7679,  ..., 0.9376, 0.4531, 0.2679],
         ...,
         [0.8334, 0.5565, 0.5071,  ..., 0.1871, 0.6318, 0.1168],
         [0.6653, 0.6452, 0.9572,  ..., 0.0050, 0.0589, 0.6159],
         [0.9485, 0.8102, 0.3728,  ..., 0.0830, 0.5617, 0.5693]],

        [[0.2361, 0.3688, 0.9160,  ..., 0.9626, 0.6881, 0.0103],
         [0.0373, 0.3465, 0.2984,  ..., 0.6758, 0.8699, 0.6337],
         [0.0763, 0.6374, 0.1366,  ..., 0.7911, 0.3950, 0.7557],
         ...,
         [0.3415, 0.3639, 0.6626,  ..., 0.4008, 0.8983, 0.7323],
         [0.9167, 0.1275, 0.5615,  ..., 0.4392, 0.6950, 0.0135],
         [0.8929, 0.0483, 0.5401,  ..., 0.5902, 0.7036, 0.0721]],

        [[0.8828, 0.8267, 0.6800,  ..., 0.6866, 0.0697, 0.6711],
         [0.7895, 0.8188, 0.9568,  ..., 0.0018, 0.7717, 0.5820],
         [0.2604, 0.8191, 0.1045,  ..., 0.8376, 0.5786, 0.

In [21]:
random_tensor_img_size.shape, random_tensor_img_size.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [22]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(2,4,5))
print(zeros)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [23]:
zeros * random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [24]:
# Create a tensor of all Ones

ones = torch.ones(2,4,4)
print(ones)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like




In [26]:
# creating tensors range

one_to_ten = torch.arange(0,11,2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [27]:
# creating tensors-like -> it replicates the shape of a tensor range

tensors_like = torch.zeros_like(one_to_ten)
tensors_like

tensor([0, 0, 0, 0, 0, 0])

In [28]:
# Float 32 tenosr

float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,
                               device= None,
                              requires_grad=False)
float_32_tensor



tensor([3., 6., 9.])

### Tensor Datatypes

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from the tensors

In [34]:
# Create a tensor

some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.9613, 0.0284, 0.7828, 0.2673],
        [0.8962, 0.5327, 0.4472, 0.6231],
        [0.8226, 0.6194, 0.6411, 0.4112]])

In [35]:
print(f'Datatype of some-tensor is: {some_tensor.dtype}')
print(f'Shape of some-tensor is: {some_tensor.shape}')
print(f'Device of some-tensor is: {some_tensor.device}')

Datatype of some-tensor is: torch.float32
Shape of some-tensor is: torch.Size([3, 4])
Device of some-tensor is: cpu


### Manipulating the tensors

In [36]:
 # Addition

add_tensor = torch.tensor([1,2,3])
add_tensor + 10

tensor([11, 12, 13])

In [37]:
# Subtraction

sub_tensor = torch.tensor([5,7,2])
sub_tensor - 5

tensor([ 0,  2, -3])

In [38]:
# Multiplication

mul_tensor = torch.tensor([5,7,2])
mul_tensor * 100

tensor([500, 700, 200])

In [39]:
# Divide

div_tensor = torch.tensor([5,7,2])
div_tensor / 10

tensor([0.5000, 0.7000, 0.2000])

In [40]:
# Matrix Multiplication

%%time

mult_tensor = torch.tensor([3,3,2])
matrix_mult = torch.matmul(mult_tensor,mult_tensor)
print(matrix_mult)

tensor(22)
CPU times: user 903 µs, sys: 988 µs, total: 1.89 ms
Wall time: 5.97 ms


In [41]:
# Matrix Multiplication using for loop

%%time

val = 0
for i in range(len(mult_tensor)):
  val += mult_tensor[i] * mult_tensor[i]
val

CPU times: user 238 µs, sys: 41 µs, total: 279 µs
Wall time: 288 µs


tensor(22)

### Rules of Matrix Multiplication
There are two main rules:
1. Inner dimensions must match
2. Resulting vector should have shape of **outer dimensions**

*    (3,2) * (3,2)   won't work
*    (3,2) * (2,3)   will work
*    (2,3) * (3,2)   will work





In [42]:
torch.matmul(torch.rand(2,10), torch.rand(10,2))

tensor([[2.9222, 1.1907],
        [2.6111, 1.5233]])

### Shapes for matrix multiplication

In [43]:
# Shapes

tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])

tensor_B = torch.tensor([[2,3],
                        [6,0],
                         [9,7]])

torch.matmul(tensor_A,(tensor_B.T))
# torch.matmul(tensor_A,tensor_B) -> gives error due to incorrect shape

tensor([[ 8,  6, 23],
        [18, 18, 55],
        [28, 30, 87]])

### Tensor Aggregation

Min, Max, Mean, Sum etc(aggregation)

In [44]:
# Find Minimim

x = torch.arange(0,100,10)
min = torch.min(x), x.min()
min, x.dtype

((tensor(0), tensor(0)), torch.int64)

In [45]:
# Find Maximum

max = torch.max(x), x.max()
max

(tensor(90), tensor(90))

In [46]:
# Find mean

mean = torch.mean(x.type(dtype=torch.float32)), x.type(torch.float32).mean()
mean

(tensor(45.), tensor(45.))

In [47]:
# Find sum

sum = torch.sum(x), x.sum()
sum

(tensor(450), tensor(450))

In [48]:
# Find argmin

argmin = torch.argmin(x), x.argmin()
argmin, x[0]

((tensor(0), tensor(0)), tensor(0))

In [49]:
# Find argmax

argmax = torch.argmax(x), x.argmax()
argmax, x[9]

((tensor(9), tensor(9)), tensor(90))

### Reshaping, Stacking, Squeezing and Unsqueezing tensors

In [50]:
# Create a tensor

y = torch.arange(1.0,11.0)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [51]:
# Reshape

y_reshaped =y.reshape(1,10)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [52]:
# Change the view
# view returns the input tensor dimensions but shares the same memory
# as original input, also changing view will change the original input

z = y.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [53]:
z[:,0] = 5
z,y

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [54]:
torch.vstack([y,y,y,y])

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [55]:
torch.hstack([y,y,y,y])

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [56]:
# Squeeze -> removes all the 1 dimensions

squeezed = torch.squeeze(y_reshaped, dim=0)
print(f"Original tensor: {y_reshaped}")
print(f"Original tensor shape: {y_reshaped.shape}")
print(f"\nSqueezed tensor: {squeezed}")
print(f"Squeezed tensor shape: {squeezed.shape}")


Original tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Original tensor shape: torch.Size([1, 10])

Squeezed tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Squeezed tensor shape: torch.Size([10])


In [57]:
# Unsqueeze -> adds the 1 dimension

unsqueezed = torch.unsqueeze(squeezed, dim=0)

print(f"Original tensor: {y}")
print(f"Original tensor shape: {y.shape}")
print(f"\nUnsqueezed tensor: {unsqueezed}")
print(f"Unsqueezed tensor shape: {unsqueezed.shape}")


Original tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Original tensor shape: torch.Size([10])

Unsqueezed tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Unsqueezed tensor shape: torch.Size([1, 10])


In [58]:
# Permute -> rearranges the dimensions of a target tensor in a specified order
# permute is a view

x_original = torch.rand(size=(224,224,3))
x_original[0,0,0] = 876
x_permuted = x_original.permute(2,0,1)
x_permuted.shape, x_permuted[0,0,0]




(torch.Size([3, 224, 224]), tensor(876.))

### Indexing (selecting data from tensors)

In [59]:
# Indexing

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
# index on first bracket

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# index on second bracket

x[0][0]

tensor([1, 2, 3])

In [62]:
# index on most inner bracket

x[0][2][2]


tensor(9)

In [63]:
# using slicing operator

x[:,0]

tensor([[1, 2, 3]])

In [64]:
x[:,1,1]

tensor([5])

In [65]:
x[0,0,:]

tensor([1, 2, 3])

In [66]:
x[0,2,2], x[0,:,2]

(tensor(9), tensor([3, 6, 9]))

### Pytorch tensors and numpy

In [67]:
# Numpy array to pytorch

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), torch.float64)

In [68]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# Pytorch to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [70]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Pytorch Reproducibility (concept of randomness)

In [71]:
rand_tensorA = torch.rand(3,4)
rand_tensorB = torch.rand(3,4)
print(rand_tensorA)
print(rand_tensorB)
print(rand_tensorA==rand_tensorB)

tensor([[0.8194, 0.2697, 0.0580, 0.7163],
        [0.2804, 0.6552, 0.3639, 0.0057],
        [0.7116, 0.2124, 0.7317, 0.3399]])
tensor([[0.4232, 0.5079, 0.1394, 0.6929],
        [0.8863, 0.0300, 0.2715, 0.5682],
        [0.7534, 0.3869, 0.5223, 0.8041]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
random_seed = 42

torch.manual_seed(random_seed)
rand_tensorC = torch.rand(3,4)
torch.manual_seed(random_seed)
rand_tensorD = torch.rand(3,4)

print(rand_tensorC==rand_tensorD)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Check for GPU access with pytorch

In [73]:
# GPU access using pytorch

torch.cuda.is_available()

False

In [74]:
# Setting an agnostic device

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [75]:
# Count the number of GPU devices

torch.cuda.device_count()

0

### Putting tensors/models on GPUs

In [76]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


### Move tensors to GPU (if available)

In [77]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### Moving tensors back to CPU

In [78]:
cpu_tensor = tensor_on_gpu.cpu().numpy()
cpu_tensor

array([1, 2, 3])

In [79]:
# Exercise 1 -> Read Documentation on torch.tensor and torch.cuda

In [80]:
# Exercise 2

rand_tensor = torch.rand(7,7)
rand_tensor, rand_tensor.shape

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 torch.Size([7, 7]))

In [81]:
# Exercise 3

rand_tensor2 = torch.rand(1,7)
matrix_mult = torch.matmul(rand_tensor, rand_tensor2.T)
matrix_mult, matrix_mult.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

In [82]:
# Exercise 4

random_seed = 0

torch.manual_seed(random_seed)
rand1 = torch.rand(7,7)
torch.manual_seed(random_seed)
rand2 = torch.rand(1,7)

matrix_mult = torch.matmul(rand1,rand2.T)
matrix_mult, matrix_mult.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [83]:
# Exericse 5

gpu_seed = torch.cuda.manual_seed(1234)

In [84]:
# Exercise 6

torch.manual_seed(1234)
gpu_tensor1 = torch.rand(2,3)
torch.manual_seed(1234)
gpu_tensor2 = torch.rand(2,3)


device = 'cuda' if torch.cuda.is_available else 'cpu'

tensors_to_gpu = gpu_tensor1.to(device)
tensors_to_gpu2 = gpu_tensor2.to(device)

print(tensors_to_gpu)
print(tensors_to_gpu2)


RuntimeError: ignored

In [85]:
# Exercise 7

gpu_tensor2 = gpu_tensor2.T
matmul = torch.matmul(gpu_tensor1, gpu_tensor2)
matmul, matmul.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]]),
 torch.Size([2, 2]))

In [86]:
# Exercise 8

print(matmul.min(), matmul.max())
print(torch.min(matmul), torch.max(matmul))

tensor(0.2161) tensor(0.6287)
tensor(0.2161) tensor(0.6287)


In [87]:
# Exercise 9

print(matmul.argmin(), matmul.argmax())
print(torch.argmin(matmul), torch.argmax(matmul))

tensor(1) tensor(3)
tensor(1) tensor(3)


In [88]:
seed = 7
torch.manual_seed(seed)
new_rand_tensor = torch.rand(size=[1,1,1,10])

print(new_rand_tensor)
print(new_rand_tensor.shape)

print(torch.squeeze(new_rand_tensor))
print(torch.squeeze(new_rand_tensor).shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
